set encoding=utf-8
scriptencoding utf-8
set shell=/bin/sh

augroup MyVimrc
  autocmd!
augroup END
command! -nargs=* AutoCmd autocmd MyVimrc <args>

let g:loaded_vimballPlugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_rrhelper = 1
let g:did_install_default_menus = 1
let g:sh_noisk = 1
if exists('$TMUX')
  " tmux will only forward escape sequences to the terminal if surrounded by a DCS sequence
  let &t_SI .= "\<Esc>Ptmux;\<Esc>\<Esc>[6 q\<Esc>\\"
  let &t_SR .= "\<Esc>Ptmux;\<Esc>\<Esc>[4 q\<Esc>\\"
  let &t_EI .= "\<Esc>Ptmux;\<Esc>\<Esc>[2 q\<Esc>\\"
else
  let &t_SI .= "\<Esc>[6 q"
  let &t_SR .= "\<Esc>[4 q"
  let &t_EI .= "\<Esc>[2 q"
endif
set incsearch
set hlsearch|nohlsearch
set backspace=indent,eol,start
set sidescrolloff=5
set scrolloff=1
set nostartofline
if &startofline
  augroup vimrc_stayput
    autocmd!
    autocmd BufLeave * set nostartofline |
          \ autocmd vimrc_stayput CursorMoved,CursorMovedI * set startofline |
          \ autocmd! vimrc_stayput CursorMoved,CursorMovedI
  augroup END
endif
set splitright
set splitbelow
set switchbuf=useopen,usetab
set wildmenu
set wildmode=longest:full,list:full
set complete=.,w,b,u,t,i,k
set omnifunc=syntaxcomplete#Complete
set completeopt=longest,menuone
set nowrap
set nobackup
set noswapfile
set pumheight=15
set number
set autoread
set shiftround
set expandtab
set showcmd
set hidden
set diffopt+=context:5,vertical,iwhite
set shortmess=atToOIc
set updatetime=750
set previewheight=20
set mouse=a
set list listchars=tab:▸\ ,trail:-,space:.,extends:>,precedes:<,nbsp:⎵,eol:↲
set showmode
set sessionoptions-=options
set timeoutlen=1200
set ttimeoutlen=50
set lazyredraw
set ttyfast
set clipboard^=unnamedplus,unnamed
function! AFTERLOAD()
  set statusline=%f\ %h%m%r%w
  set laststatus=2
  if exists('g:loaded_fugitive')
    set statusline+=%{fugitive#head()}
  endif
  set statusline+=%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)
endfunction
AutoCmd FileType * call AFTERLOAD()
command! StatusDebug set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
command! StatusNormal call AFTERLOAD()
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif
filetype plugin indent on

nnoremap <Esc><Esc> :nohlsearch<CR>
" Jump to start of function
nnoremap ]] ]m
nnoremap [[ [m

" Grep for word under the cursor
if executable('rg')
        set grepprg=rg\ --vimgrep
elseif executable('ag')
        set grepprg=ag\ --nogroup\ --nocolor\ --ignore-case\ --column
endif
set grepformat=%f:%l:%c:%m,%f:%l:%m

AutoCmd BufEnter,CursorHold,CursorHoldI,CursorMoved,CursorMovedI,FocusGained,BufEnter,FocusLost,WinLeave * checktime
AutoCmd BufEnter * syntax sync minlines=99999
AutoCmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line('$') | exe 'normal! g`"zz' | endif

nnoremap <Esc><Esc> :nohlsearch<CR>
nnoremap j gj
nnoremap k gk
vnoremap > >gv
vnoremap < <gv
nnoremap <C-s> :update<CR>
inoremap <C-s> <Esc>:update<CR>
nnoremap <C-q> :bwipeout<CR>
nnoremap ,q :bdelete<CR>
" nnoremap <silent><expr> q winnr('$') != 1 ? ':<C-u>close<CR>' : ""
xnoremap <C-s> <C-C>:<C-u>update<CR>
nnoremap <expr> 0 virtcol('.') - 1 <= indent('.') && col('.') > 1 ? '0' : '_'
nnoremap H ^
nnoremap L $
vnoremap L g_
nnoremap <silent> <Tab>      :wincmd w<CR>
nnoremap <silent> <S-Tab>      :wincmd W<CR>
nnoremap <silent> <C-Up> : resize -1<CR>
nnoremap <silent> <C-Down> : resize +1<CR>
nnoremap <silent> <C-Left> :vertical resize +1<CR>
nnoremap <silent> <C-Right> :vertical resize -1<CR>
vnoremap . :normal .<CR>
nnoremap ,w :set wrap!<cr>
nnoremap <Leader>w :%s/\s\+$//e<CR>
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
inoremap <C-a> <Home>
inoremap <C-e> <End>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <Space><Space> :tabnew %<CR>
nnoremap <Space>q :tabclose<CR>
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
function! s:VSetSearch()
  let l:temp = @@
  norm! gvy
  let @/ = '\V' . substitute(escape(@@, '\'), '\n', '\\n', 'g')
  let @@ = l:temp
endfunction
vnoremap * :<C-u>call <SID>VSetSearch()<CR>//<CR><c-o>
vnoremap # :<C-u>call <SID>VSetSearch()<CR>??<CR><c-o>

map [1;5A <C-Up>
map [1;5B <C-Down>
map [1;5C <C-Left>
map [1;5D <C-Right>
map [1;2A <S-Up>
map [1;2B <S-Down>
map [1;2C <S-Right>
map [1;2D <S-Left>

command! RemoveTrailingSpaces %s/\s\+$

colorscheme apprentice
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']

let g:clever_f_ignore_case = 1
let g:clever_f_smart_case = 1
let g:clever_f_fix_key_direction = 1

let g:ctrlp_max_files = 0
let g:ctrlp_working_path_mode = ''
let g:ctrlp_switch_buffer = 0
let g:ctrlp_use_caching = 0
let g:ctrlp_show_hidden = 1
let g:ctrlp_open_multi = '1v'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'
nnoremap <C-p> :packadd ctrlp.vim<CR>:CtrlP<CR>
nnoremap <Bs> :packadd ctrlp.vim<CR>:CtrlPBuffer<CR>
nnoremap <C-_> :packadd ctrlp.vim<CR>:CtrlPMRUFiles<CR>
nnoremap <C-d> :packadd ctrlp.vim<CR>:CtrlPCurFile<CR>

let g:ale_sign_error = '→'
let g:ale_sign_warning = '→'
let g:ale_sign_info = 'i'
let g:ale_pattern_options_enabled = 1
let g:ale_fixers = {
      \ 'javascript': ['eslint'],
      \ 'html': ['eslint']
      \}
let g:ale_fix_on_save = 1
let g:ale_linters = {
      \ 'javascript': ['eslint'],
      \ 'html': ['eslint'],
      \}
let g:ale_linter_aliases = {
      \ 'html': 'javascript',
      \}
let g:sneak#label = 1
nmap s <Plug>SneakLabel_s
nmap S <Plug>SneakLabel_S
let g:netrw_banner=0
let g:netrw_liststyle = 3

let g:ScalpelCommand='S'
